export const shipmentsData = [
  {
    name: "Lisa Jerardo",
    date: "April 10th - May 17th",
    room: "Quail Room",
    star: 4.1,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 1,
    avatar: "/requests-avatars/request-avatar1.png",
  },
  {
    name: "Orlando Diggs",
    date: "April 14th - June 30th",
    room: "Canary Room",
    star: 3.2,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 2,
    avatar: "/requests-avatars/request-avatar2.png",
  },
  {
    name: "Andi Lane",
    date: "May 16th - July 4th",
    room: "Bluejay Room",
    star: 4.4,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 2,
    avatar: "/requests-avatars/request-avatar3.png",
  },
  {
    name: "Eva Leroy",
    date: "July 7th - July 12th",
    room: "Quail Room",
    star: 5,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 4,
    avatar: "/requests-avatars/request-avatar4.png",
  },
  {
    name: "Andi Lane",
    date: "May 16th - July 4th",
    room: "Bluejay Room",
    star: 4.4,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 5,
    avatar: "/requests-avatars/request-avatar3.png",
  },
  {
    name: "Orlando Diggs",
    date: "April 14th - June 30th",
    room: "Canary Room",
    star: 3.2,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 6,
    avatar: "/requests-avatars/request-avatar2.png",
  },
  {
    name: "Eva Leroy",
    date: "July 7th - July 12th",
    room: "Quail Room",
    star: 5,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 7,
    avatar: "/requests-avatars/request-avatar4.png",
  },
  {
    name: "Andi Lane",
    date: "May 16th - July 4th",
    room: "Bluejay Room",
    star: 4.4,
    quantity: 10,
    weight: 55,
    price: 550.99,
    id: 8,
    avatar: "/requests-avatars/request-avatar3.png",
  },
];

export const messageData = [
  {
    id: 1,
    name: "Rene Wells",
    message: "This is my message to about the request",
    time: "7:21AM",
    status: "read",
    avatar: "/requests-avatars/message-avatar1.png",
  },
  {
    id: 2,
    name: "Joshua Wilson",
    message: "Randomly thought about checking in on the request",
    time: "7:08AM",
    status: "read",
    avatar: "/requests-avatars/message-avatar2.png",
  },
  {
    id: 3,
    name: "Lori Bryan",
    message: "I'll like to visit in November, is that possible?",
    time: "Yesterday",
    status: "unread",
    avatar: "/requests-avatars/message-avatar3.png",
  },
  {
    id: 4,
    name: "Anaiah Williams",
    message: "Do you have any heating?",
    time: "Yesterday",
    status: "read",
    avatar: "/requests-avatars/message-avatar4.png",
  },
  {
    id: 5,
    name: "Noah Pierre",
    message: "Yes",
    time: "Yesterday",
    status: "read",
    avatar: "/requests-avatars/message-avatar5.png",
  },
  {
    id: 6,
    name: "Katherine Moss",
    message: "No, I would like to add that into the request",
    time: "Yesterday",
    status: "read",
    avatar: "/requests-avatars/message-avatar6.png",
  },
  {
    id: 7,
    name: "Edward Franz",
    message: "Cool, I will book now!",
    time: "3/26/23",
    status: "unread",
    avatar: "/requests-avatars/message-avatar7.png",
  },
  {
    id: 8,
    name: "Alec Whitten",
    message: "I just have a shower with a curtain",
    time: "3/26/23",
    status: "read",
    avatar: "/requests-avatars/message-avatar8.png",
  },
];
