import { MapPinned, Truck, Network, Album, LandPlot } from "lucide-react";

export const vendorTableData = [
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "Before Service",
    days: 50,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "Before Service",
    days: 23,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "Before Service",
    days: 60,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 40,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 14,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 34,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 44,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 54,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "After Service",
    days: 71,
    due: 50,
  },
  {
    invoiceID: "#AHGA68",
    date: "23/09/25",
    name: "Jacob Marcus",
    service: "Before Service",
    days: 50,
    due: 50,
  },
];

export const shipmentDetails = [
  {
    id: 1,
    title: "ORIGIN PORT",
    content: "Kaduna, Nigeria",
    icon: <MapPinned />,
  },
  {
    id: 2,
    title: "DESTINATION PORT",
    content: "Marrakech, Morocco",
    icon: <LandPlot />,
  },
  {
    id: 3,
    title: "SHIPPER",
    content: "Ubuntu Shipping LLC",
    icon: <Truck />,
  },
  {
    id: 4,
    title: "CONSIGNEE",
    content: "Afiim Shippers",
    icon: <Network />,
  },
  {
    id: 5,
    title: "BOOKING DATE",
    content: "Feb 3, 2025",
    icon: <Album />,
  },
];

export const vendorPaymentsData = [
  {
    id: 1,
    services: "Shipment Charge",
    amount: "$23,42.00",
    vendor: "Area Logistics",
    status: "Paid",
    force: "/green-point.png",
    paymentDate: "N/A",
  },
  {
    id: 2,
    services: "Logistics Fees",
    amount: "$64,63.00",
    vendor: "Ubuntu's Port Incorporated",
    status: "Pending",
    force: "/red-point.png",
    paymentDate: "Jan 10, 2025 1:11 PM",
  },
  {
    id: 3,
    services: "Procurement",
    amount: "$42,11.09",
    vendor: "Procurement Incorporated",
    status: "Pending",
    force: "/red-point.png",
    paymentDate: "Jan 23, 2025 1:24 PM",
  },
  {
    id: 4,
    services: "Shipment Charge",
    amount: "$23,42.00",
    vendor: "Area Logistics",
    status: "Paid",
    force: "/green-point.png",
    paymentDate: "N/A",
  },
  {
    id: 5,
    services: "Logistics Fees",
    amount: "$64,63.00",
    vendor: "Ubuntu's Port Incorporated",
    status: "Pending",
    force: "/red-point.png",
    paymentDate: "Jan 10, 2025 1:11 PM",
  },
  {
    id: 6,
    services: "Procurement",
    amount: "$42,11.09",
    vendor: "Procurement Incorporated",
    status: "Pending",
    force: "/red-point.png",
    paymentDate: "Jan 23, 2025 1:24 PM",
  },
];
